Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
  # If you want the rule only apply to a specific folder/file